name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust GitHub’s host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Rimworld DLL
        working-directory: ../..
        run: |
          git clone git@github.com:JalapenoLabs/RimworldDll.git RimWorldWin64_Data

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Dotnet restore
        run: dotnet restore .vscode

      - name: Build
        run: dotnet build .vscode

      - name: Validate XML (xmllint)
        uses: phpcsstandards/xmllint-validate@v1
        with:
          pattern: "1.6/Defs/**/*.xml"
          show-in-pr: true

      - name: Validate XML (xmllint)
        uses: phpcsstandards/xmllint-validate@v1
        with:
          pattern: "About/About.xml"
          show-in-pr: true
